### ISSUE TITLE
Java 8 support (Java 7 sunsets April 2015)

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-application-modules#116]
Seems like we just moved to Java 7, but Oracle is [discontinuing support for Java 7](http://www.oracle.com/technetwork/java/eol-135779.html) in April 2015:

> **Auto-update Notice and End of Public Updates for Oracle JDK 7**
> As outlined in the Oracle JDK Support Roadmap, after April 2015, Oracle will not post further updates of Java SE 7 to its public download sites. Customers who need continued access to critical bug fixes and security fixes as well as general maintenance for Java SE 7 or older versions can get long term support through Oracle Java SE Support. The process of migrating users from Java 7 to Java 8 through the auto update feature is expected to take place after the January 2015 CPU release.

Additionally, as mentioned in the last sentence, users will start to get updated to Java 8 automatically very soon.  We should evaluate whether there are any issues running OBA on Java 8, and if not, migrate to Java 8 as the default Java version.

**Comment by kurtraschke** [comment]
OBA appears to build and run fine on Java 8; at some point we should bump the Java source version to 1.8 in the parent POM (onebusaway/onebusaway#8).

**Comment by barbeau** [comment]
Thanks @kurtraschke, good to know.  What components did you test?  Does this include the unit tests also?

IIRC, we hit an issue with the QuickStart bundle when bumping from Java 6 to 7.  It would be nice to  test all the major components (including some of the other projects that depend on the parent POM) before bumping from 7 to 8 in master.

On a related note, we also have the option of running Travis CI with Java 6, Java 7, Java 8, or any combination of the above.  To do this the following can be added to the [`.travis.yml`](https://github.com/OneBusAway/onebusaway-application-modules/blob/master/.travis.yml) config file, for each of the Java versions we want to run:

~~~
jdk:
  - oraclejdk8
  - oraclejdk7
~~~

By default it currently runs on Java 7.

**Comment by kurtraschke** [comment]
I did a clean build of `onebusaway-application-modules`, so the unit tests ran; I've also run the quickstart under Java 8 without any issues that weren't also reproducible under Java 7.

**Comment by mpaine-act** [comment]
Old issue, still open: is anyone successfully using Java 9/10 with OBA?

**Comment by aaronbrethorst** [comment]
Current builds require JDK 11, iirc.
