### ISSUE TITLE
Vehicle occupancy and stops' crowd size real-time data feed

### ISSUE THREAD

**Issue by drabell** [OneBusAway/onebusaway-application-modules#124]
<i>Question 1</i>: Is it possible to track in real-time mass-transit vehicle(s) occupancy pertinent to a selected Route (e.g. MTA M1)? If so, what is the format of web query and response structure?
<i>Question 2</i>: Is it possible to establish bi-directional data communication channel (which implements crowd-sourcing data aggregator) to report/retrieve in real-time the approximate size of the crowd at certain MTA Bus stop(s)?
Thanks and regards, Alexander

**Comment by laidig** [comment]
Sorry, Passenger counting is not supported by OBA or MTA Bus Time at the moment.

**Comment by drabell** [comment]
OK, thanks.

**Comment by barbeau** [comment]
For those stumbling on this ticket later, I have opened https://github.com/OneBusAway/onebusaway-application-modules/issues/121 for general support for the GTFS-rt OccupancyStatus field in OBA.  We plan to use this in Tampa, but AFAIK no other current OBA regions, including NYC, have the vehicle hardware to support this.
