### ISSUE TITLE
Per-stoptime predictions - downstream vehicle deviations are propagated to upstream stops

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-application-modules#127]
For `develop` branch:

PR https://github.com/OneBusAway/onebusaway-application-modules/pull/78 was merged a while back to the `develop` branch that added support to the TDS for per-stoptime predictions (thanks again @kurtraschke!).  

To quote that PR:

>This PR adds support for preserving those per-stoptime predictions from GTFS-realtime sources and passing them through the TDS. It also adds support for exposing those per-stoptime predictions in the GTFS-realtime exporters in the API webapp and TDS.

>The API webapp and legacy Web interface do not make direct use of these per-stoptime predictions, but they can be used by the OBANYC SIRI API and Web UIs with a suitable PredictionHelperService (patch forthcoming).

The GTFS-rt feed we're working with for a new agency for OBA Tampa provides per-stoptime updates:
http://97.76.252.61:8080/gtfsrt/trips?debug

As we discussed with @sheldonabrown today, we'd like to expose these per-stop predictions via the onebusaway-api-webapp so the apps (Android, iOS, and Windows Phone) show these predictions to users.

@kurtraschke Any feedback on best implementation for this?  @sheldonabrown is planning to look at this in the upcoming month or so, and any advice is much appreciated.

cc @cagryInside

**Comment by kurtraschke** [comment]
So I've just done some digging in the code, and I believe I may have been mistaken in my earlier assertion that the legacy API and UI would not use per-stoptime predictions.  If we start from `ArrivalAndDepartureServiceImpl.getBestScheduleDeviation()`, if per-stoptime predictions exist in the `BlockLocation` (`blockLocation.getScheduleDeviation()`), then it will interpolate from the supplied schedule deviations to use the 'closest' values to the stoptime whose deviation is being determined.  Following the data brings us to `BlockLocationServiceImpl`, where `getBlockLocation()` will indeed populate the `BlockLocation` with a `ScheduleDeviationSamples` object which is populated from the incoming `VehicleLocationRecord`'s `TimepointPredictionRecord` elements.

**Comment by cagryInside** [comment]
Currently we are testing a new agency (```PSTA```) for OBA Tampa which provides per-stoptime updates.
The GTFS-rt data returns 2 real-time stop updates for ```StopId:1624```:

```
entity {
  id: "157"
  trip_update {
    trip {
      trip_id: "1208465020"
      route_id: "CAT"
    }
    stop_time_update {
      arrival {
        time: 1435002867
      }
      stop_id: "1623"
    }
    stop_time_update {
      arrival {
        time: 1435002909
      }
      stop_id: "1624"
    }
....
}


entity {
  id: "180"
  trip_update {
    trip {
      trip_id: "1208466020"
      route_id: "CAT"
    }
    stop_time_update {
      arrival {
        time: 1435003926
      }
      stop_id: "1624"
    }
...
}

```

However, OBA Android application shows three different arrival times:
![device-2015-06-22-160728](https://cloud.githubusercontent.com/assets/2777974/8291739/6f27f3e0-18f9-11e5-88c2-773a5c18b053.png)

GTFS-rt data contains the stopId for first two trips. However, the GTFS-rt data doesn't include the stopId for the last trip(```TripId: PSTA_1208467020```). Also, in ```GTFS data stop_times.txt```  the trip with ```TripID = 1208467020``` doesn't have the stopId (``` 1624```).

**Comment by barbeau** [comment]
Also, the above is running the `develop` branch.

**Comment by barbeau** [comment]
@kurtraschke or @sheldonabrown Is the code from #78 that preserves per-stop predictions running in the current OBA NYC?  Just curious - from the issue comments it sounds like there is still pending work there that hasn't yet been completed (from Kurt - "they can be used by the OBANYC SIRI API and Web UIs with a suitable PredictionHelperService (patch forthcoming)").  There seems to be adverse effects to using the code with the OBA api-webapp and legacy webapp, as @cagryInside shows above.  We're trying to dig in and see what exactly is going wrong.

**Comment by barbeau** [comment]
We've been troubleshooting this further - it appears we made an error when saying that trips are showing up that don't visit that stop (trip_id PSTA_1208467020 does include stop_id 1624), so that's not an issue.

@kurtraschke seems to be correct in that the per-stop predictions are exposed via the onebusaway-api-webapp.  So, that's good!

The main problem we're seeing now is that it appears that OBA is erroneously interpolating per-stop predictions when the stop is upstream of the provided per-stop stop_time_updates, which results in deviations being propagated *upstream*.  This manifests in the UI as a trip continuously being shown after the bus passes the stop, with a delay value that continues to grow until the bus is complete with that trip (see below - in the 2nd entry with the 20 min delay, the bus has already passed this stop for that trip).

![image](https://cloud.githubusercontent.com/assets/928045/8478283/5558e1c0-209e-11e5-8fab-6b66e36dd1c4.png)

I'm going to change this issue name to reflect this problem.

@cagryInside is working on a patch and some unit tests to try and resolve this issue.

**Comment by barbeau** [comment]
FYI - current work on this issue is happening in https://github.com/CUTR-at-USF/onebusaway-application-modules/tree/develop-psta2

**Comment by barbeau** [comment]
So I think we understand better why the downstream bus was being shown on an upstream stop it had already passed.  When processing the per stop predictions from GTFS-rt TripUpdates and indexing them as deviations , there is a code block in [`BlockLocationServiceImpl`](https://github.com/OneBusAway/onebusaway-application-modules/blob/develop/onebusaway-transit-data-federation/src/main/java/org/onebusaway/transit_data_federation/impl/realtime/BlockLocationServiceImpl.java#L569): 

~~~
for (BlockStopTimeEntry blockStopTime : blockConfig.getStopTimes()) {
        StopTimeEntry stopTime = blockStopTime.getStopTime();
        StopEntry stop = stopTime.getStop();
        if (stopId.equals(stop.getId())) {  // Check for matching stopIds
          int arrivalTime = stopTime.getArrivalTime();
          int deviation = (int) ((tpr.getTimepointPredictedTime() - blockInstance.getServiceDate()) / 1000 - arrivalTime);
          scheduleDeviations.put(arrivalTime, (double) deviation);
        }
}
~~~

For each GTFS-rt prediction, it searches down the entire block and if the stopId of the prediction matches the stopId, it saves the deviation for that stop.

The problem is that our block contained a loop, with the same stopId being visited in more than one trip in the block.  As a result, the deviation was incorrectly being saved for more than one stop.

We plan to fix this by checking of the tripId and making sure they match before adding the deviation:

    if (stopId.equals(stop.getId()) && stopTime.getTrip().getId().equals(tpr.getTripId())) {   // Check for matching stopId AND tripId

This also requires adding the tripId to the `TimepointPredictionRecord` when consuming the GTFS-rt TripUpdates so we can reference it here.  This seems to resolve the problem in our testing.

If anyone sees any potential problem in this please let us know.

**Comment by kurtraschke** [comment]
Does it make sense to extend this to use `stop_sequence` where available, in the event a trip loops back on itself?

**Comment by barbeau** [comment]
@kurtraschke Good idea - yes, I believe it would make sense to include `stop_sequence` in the IF statement as well.

**Comment by barbeau** [comment]
We're working on tests for this and the other per stop prediction issues.

To really get good coverage on the code that's responsible for consuming the real-time predictions and showing correct arrival/departure information, we need to pass data through both [`BlockLocationServiceImpl`](https://github.com/OneBusAway/onebusaway-application-modules/blob/develop/onebusaway-transit-data-federation/src/main/java/org/onebusaway/transit_data_federation/impl/realtime/BlockLocationServiceImpl.java#L569) and [`ArrivalAndDepartureServiceImpl`](https://github.com/OneBusAway/onebusaway-application-modules/blob/develop/onebusaway-transit-data-federation/src/main/java/org/onebusaway/transit_data_federation/impl/ArrivalAndDepartureServiceImpl.java#L649), and then compare the input to the output.  For example, there in an assumption made in `ArrivalAndDepartureServiceImpl` that indexes for the schedule deviations are scheduled *arrival* times, but the actual indexing of deviations with arrival times is done in `BlockLocationServiceImpl`.  There should be some test for this that breaks if that assumption is ever changed.

So far it seems like most OBA tests we've looked at are unit tests, and not along the lines of higher level integration/functional tests, which is what we're trying to do here.

@cagryInside has been trying to create such a test, but has been running into issues mocking some of the cache elements.

@bdferris @kurtraschke @sheldonabrown Any ideas on how this should/can be done, or pointers to other tests in OBA that do this?

**Comment by barbeau** [comment]
I think we've figured out the caching issue.  We are pulling together some units tests now and should be opening a PR in the near future.

**Comment by barbeau** [comment]
This was fixed in https://github.com/OneBusAway/onebusaway-application-modules/pull/142, which has been merged into `develop` branch, so I'm closing this.
