### ISSUE TITLE
FederatedTransitDataBundleCreatorMain does not recognise listed option : useDatabaseForGtfs

### ISSUE THREAD

**Issue by scrudden** [OneBusAway/onebusaway-application-modules#137]
Unrecognized option: -useDatabaseForGtfs

This is listed in the usage as one of the command line options. 

The buildOptions method in FederatedTransitDataBundleCreatorMain does not add this as an option so an exception is thrown when parsing the command line arguments.

**Comment by zhumingvictor** [comment]
Same problem here. After reading the source code "useDatabaseForGtfs" isn't added as a valid option.

**Comment by russellhoff** [comment]
Same problem here. What I want is to add GTFS data to my database (postgresql), calling this: PS C:\......> java -jar .\onebusaway-transit-data-federation-builder-1.1.14-withAllDependencies.jar -useDatabaseForGtfs -dataSourceDriverClassName="org.postgresql.Driver" -dataSourceUrl="http://localhost:5432/org_onebusaway_database" -dataSourceUsername="postgres" -dataSourcePassword="passwd" .\
lurraldebus_euskotren_bus.zip

**Comment by themonki** [comment]
This need close by OneBusAway@65f4ec3?

**Comment by sheldonabrown** [comment]
Thanks for the reminder.
