### ISSUE TITLE
Better support for filtering arrival/departure info at stops

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-application-modules#148]
In a few different discussions lately, the topic of how OneBusAway presents arrival/departure information at particular stops has come up.  Here's one on the OBA dev list:
https://groups.google.com/forum/#!topic/onebusaway-developers/xJpNO7n4EWo

**Symptom:**

Scheduled loop routes where the trip originates and terminates at the same stop show up as two different departures in OBA, and a much better presentation would be a single departure record:

![image](https://cloud.githubusercontent.com/assets/928045/9767131/a4e9a62a-56ea-11e5-974a-affabc15a5d0.png)

A separate but related issue is how arrivals/departures are shown for end-of-the-line stops, where for example a vehicle arrives at a transit center as the "18 Clearwater" trip, has a layover, and then departs as the "18 St. Pete" trip.  OBA arguably shows correct info for this when real-time data is available - it shows one record for the arriving trip, and one for the departing, and doesn't label whether these are arriving or departing.  However, we're seeing that when real-time data isn't available, OBA will incorrectly show the incoming route as a "scheduled departure" - see below for the "18 Clearwater" at 7:30am - this should say "scheduled arrival":

![image](https://cloud.githubusercontent.com/assets/928045/9767252/4f4bbfcc-56eb-11e5-9ce3-db5ec955dd57.png)

**Underlying problem:**

The following seems to be the underlying problem that's related to both issues - in the GTFS spec, `arrival_time` and `departure_time` in `stop_times.txt` are both required fields, even for the last stop in the trip.  GTFS says if you don't have a `departure_time`, you should fill in this field with the `arrival_time` value.  So, these trips that terminate at the stop actually have a scheduled departure time for that stop - OBA simply passes that departure time back in [arrivals-and-departures-for-stop](http://developer.onebusaway.org/modules/onebusaway-application-modules/current/api/where/methods/arrivals-and-departures-for-stop.html) REST API responses, and then leaves it up to the client for how that information should be displayed.  However, at this point the client doesn't have enough information to know which trips terminate at the stop in question - and, as a result, its forced to treat it as a normal stop and show departure info for the terminating trip as well.

**Possible solution:**

One potential way to handle this is to pass back another field in the [arrivals-and-departures-for-stop](http://developer.onebusaway.org/modules/onebusaway-application-modules/current/api/where/methods/arrivals-and-departures-for-stop.html) API response called `lastStop`, which is set to `true` for trips where the stop queried is the last stop in that trip:

```
arrivalsAndDepartures: [
{
serviceDate: 1441771200000,
vehicleId: "Hillsborough Area Regional Transit_1305",
lastStop: true,  // <-----New field
routeId: "Hillsborough Area Regional Transit_5",
stopSequence: 61,
routeShortName: "5",
arrivalEnabled: true,
distanceFromStop: -49.022019786178134,
scheduledArrivalTime: 1441815660000,
status: "default",
tripId: "Hillsborough Area Regional Transit_98691",
routeLongName: "40th Street",
tripHeadsign: "North to University Area TC",
predicted: true,
predictedArrivalTime: 1441815660000,
departureEnabled: true,
predictedDepartureTime: 1441815660000,
stopId: "Hillsborough Area Regional Transit_6497",
```

Clients would then have enough information to potentially filter out these departure times from view, and even hide the arrivals if desired to simplify to presentation to riders.  Bottom line, it would give OBA clients better control over how this information is presented to users.

Thoughts?  Any better ideas of how to handle this?

cc'ing @landonreed due to his post on the OBA dev list
cc @cagryInside

**Comment by barbeau** [comment]
@sheldonabrown How is scheduled time shown in the [new OBA Tampa site](http://tampa.onebusaway.org/enterprise/#6968)?  Does this issue affect that UI?  It seems for real-time it shows a time and doesn't specify whether its arriving or departing (which is the same behavior as onebusaway-webapp, and arguably correct), but I haven't been able to catch a scheduled time there yet.

**Comment by barbeau** [comment]
Of course, right after I post that a scheduled time comes up:

![image](https://cloud.githubusercontent.com/assets/928045/9768304/bfac0ef2-56f0-11e5-8fa7-f1462a791b47.png)

So it looks like arrival/departure time isn't differentiated there either.  So, I believe this UI would still have the loop trip issue, but doesn't appear to have the "scheduled departure" issue for end-of-the-line stops w/ one trip incoming and one trip outgoing.

**Comment by landonreed** [comment]
@barbeau thanks for laying this all out in issue format!

I like the proposal to indicate whether the `arrivalsAndDepartures` entity is a last stop or not.  However, I wonder if there is a more general way to represent this that handles **not only the last stop in a trip, but also the first stop in a trip.**

**Rationale:**
The `lastStop` boolean takes care the ability to filter unwanted departures from the *trip terminus*, but it fails to also filter unwanted arrivals at the *trip origin*.

This may be a minor point, but if we look at the original OBA interface, a user can view arrival times or departure times.

![image](https://cloud.githubusercontent.com/assets/2370911/9769996/82ee9c40-56fb-11e5-9fec-12df8f61ef92.png)

**Modification:**
My modification would be to have a more general attribute attached to the `arrivalsAndDepartures` entity.  Something like `tripEndpoint`, that could have three integer values:

* `0` - neither first nor last stop
* `1` - first stop in trip
* `2` - last stop in trip

I'm not entirely sold on the three values I selected above.  Maybe they should just be strings (`first`, `last`, `no`).

Thoughts?

**Comment by barbeau** [comment]
@landonreed We do currently have a `stopSequence` value in the response (see [this](http://api.tampa.onebusaway.org/api/where/arrivals-and-departures-for-stop/Hillsborough%20Area%20Regional%20Transit_6497.json?key=TEST) for a sample).  Note that this is NOT the GTFS `stop_sequence` (this confused me for a while), but an internally generated 0-indexed value.  So, whenever `stopSequence = 0`, it means that the stop is the first in the trip.

I think between the new `lastStop=true` and `stopSequence=0` that would give us enough info for clients to intelligently filter arrivals/departures at first/last stops.

**Comment by landonreed** [comment]
@barbeau ah, I see.  I didn't realize the `stop_sequence` value did not equate to the GTFS value.  In that case, your original proposal sounds good to me!

**Comment by barbeau** [comment]
Thinking more about this - a more general solution would be to include a new `totalStopsInTrip` element, instead of the `lastStop=true` element.  And, when `stopSequence + 1 = totalStopsInTrip`, this would indicate that the stop is the last stop in the trip.  With this solution, we'd also know how far along any given stop is in the trip, which could be useful.

We'd definitely want to update [the docs](http://developer.onebusaway.org/modules/onebusaway-application-modules/current/api/where/elements/arrival-and-departure.html) to say that `stopSequence` is 0-indexed, to avoid clients making off-by-one errors (and, we should also clarify in the docs that `stopSequence` != GTFS `stop_sequence`).

**Comment by barbeau** [comment]
@cagryInside just opened a PR for the new `totalStopsInTrip` element - https://github.com/OneBusAway/onebusaway-application-modules/pull/149.

**Comment by rdc517** [comment]
Works great.

"stopSequence": 46,
"totalStopsInTrip": 47,

Now... how do we use that to limit results on the OBA web and sign?

**Comment by barbeau** [comment]
@rdc517 The `onebusaway-webapp` (and all other clients) would need to be modified to filter out the arrivals/departures we don't want users to see, for both loop and the end-of-stop trips, based on the `stopSequence` and `totalStopsInTrip` values.  That would take place in another issue/PR per client - any volunteers ;)?

Unfortunately I haven't delved into the `onebusaway-webapp` client code myself, and I believe others have been avoiding it also because of the GWT dependencies.  We don't have a huge motivation here in Tampa to fix it in the `onebusaway-webapp` UI, as HART is moving to the [OBA NYC-style interface](http://tampa.onebusaway.org/enterprise/).  So, personally I'd be more inclined to fix the loop issue in the OBA NYC and other mobile clients before spending time on the `onebusaway-webapp`, but others may have other priorities.

**Comment by rdc517** [comment]
"avoiding it also because of the GWT dependencies."

heh... exactly.

I am poking through oba-webapp stuff now.  I'll take a look at NYC later too.

I can't believe this has never come up.  Is no one is using large format displays at transit centers?

Thanks again.

**Comment by barbeau** [comment]
Also, for the record, the related client issue in OBA Android is https://github.com/OneBusAway/onebusaway-android/issues/287.

**Comment by barbeau** [comment]
I should also mention that I believe Sound Transit is not running the onebusaway-webapp that's in the master branch of this project - they did a port from GWT to plain javascript and the Google Maps API v3, and AFAIK that never got merged back to master.  See https://github.com/OneBusAway/onebusaway-application-modules/issues/26#issuecomment-29024044 for details, including a link to their ported onebusaway-webapp.

**Comment by barbeau** [comment]
@landonreed and @rdc517 if you have public-facing deployments of OBA that include the https://github.com/OneBusAway/onebusaway-application-modules/pull/149 code, could you post the URLs to the problem routes (loops especially) to this thread?  It will make it easier to fix these issues on the clients if there are readily available real-world examples to work with.

**Comment by rdc517** [comment]
barbeau... we do have the sign feed available, but the display may be confusing to developers

To try and alleviate this issue asap, I made some changes to the stop_headsign fields in the GTFS feed.  All trips ending at the transit center where a sign is located now read "Arrival at Transit Center", while the departing trips simply show the destination.

I have changed the display txt that read  "arrived on time/late/early" and "departed on time/late/early" both read "was on time/late/early"

![capture3](https://cloud.githubusercontent.com/assets/9332120/9968087/5085b462-5dfb-11e5-9e06-76c8221e31e3.PNG)


I also changed "scheduled arrival" and "scheduled departure"  text on the signs to both read "scheduled time". 

![capture4](https://cloud.githubusercontent.com/assets/9332120/9968192/f000888c-5dfb-11e5-9b77-22334fbae94c.PNG)

**Comment by landonreed** [comment]
The link to the Inman Park MARTA Station [here](http://atlanta.onebusaway.org/where/standard/stop.action?id=MARTA_901155) will show Route 6, which arrives at the station with the headsign `Inman Park Station` and then immediately departs to `Lindbergh Station`.

**Comment by barbeau** [comment]
For posterity, here's a loop route soon-to-be in our OBA Tampa instance that's affected by this issue:
http://app.staging.obahart.org/where/standard/stop.action?id=PSTA_1756&route=PSTA_32

Customer facing headsign is "32 Williams Park":

![image](https://cloud.githubusercontent.com/assets/928045/12958721/1abc4a08-d001-11e5-9f61-2888ad87ee9e.png)

![image](https://cloud.githubusercontent.com/assets/928045/12958747/3452eada-d001-11e5-8da5-760a46bf0d07.png)

**Comment by barbeau** [comment]
Also please note that if you're providing real-time data for a loop route, you should be including `stop_sequence` in your real-time predictions feed.  If you don't, OBA doesn't know to which instance of the stop a prediction should be applied - see https://github.com/OneBusAway/onebusaway-application-modules/issues/163.

**Comment by barbeau** [comment]
HART loop routes in OBA Tampa:
* 96 - http://tampa.onebusaway.org/where/standard/stop.action?id=Hillsborough%20Area%20Regional%20Transit_6968&route=Hillsborough%20Area%20Regional%20Transit_96
* http://tampa.onebusaway.org/where/standard/#m(query)q(570)qll(27.9769,-82.4459)_(0)

**Comment by barbeau** [comment]
PR at https://github.com/OneBusAway/onebusaway-application-modules/pull/149.
