### ISSUE TITLE
Agency endpoint down

### ISSUE THREAD

**Issue by joelverhagen** [OneBusAway/onebusaway-application-modules#157]
The [agency](http://developer.onebusaway.org/modules/onebusaway-application-modules/current/api/where/methods/agency.html) endpoint for, say, King County Metro seems broken.

http://api.pugetsound.onebusaway.org/api/where/agency/1.xml?key=TEST

```
There is no Action mapped for namespace /api/where/agency and action name 1.
```

**Comment by sheldonabrown** [comment]
Confirmed.  Some work we introduced with agency metadata is conflicting
with the agency namespace.

**Comment by sheldonabrown** [comment]
Everything else seems ok -- this issue is specific to a single API.

**Comment by joelverhagen** [comment]
The URL in my original post works now. I've long since moved on to other projects but the URL seems fine now.
