### ISSUE TITLE
Real-time predictions for loop routes aren't matched correctly if stop_sequence is missing

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-application-modules#163]
_For `develop` branch:_

Currently, if a stop is visited more than once as part of a trip (e.g., a loop route):
- `stop_id = 1756, stop_sequence=1`
- `…`
- `stop_id = 1756, stop_sequence=99`

...and the real-time producer doesn't provide `stop_sequence` for predictions on this trip that reference the duplicate stop (`1756` above), OneBusAway doesn't apply the real-time predictions for this trip correctly, as it doesn't know to which instance of the stop the prediction should be applied (i.e., the prediction is ambiguous).  

This really isn't a bug in OneBusAway but a deficiency in the real-time data - however, the GTFS-realtime spec doesn't currently explicitly say that stop_sequence must be provided if a stop is visited more than once in a trip.  I've written a proposal to clarify that here - https://github.com/google/transit/pull/20.

We can attempt to workaround this for predictions for the first/last stops in loop routes by inferring to which stop a prediction should be applied if multiple StopTimeUpdates are provided in the feed.

For example, if there is a prediction after `stop_id = 1756` in the feed:

```
trip_update {
    trip {
      trip_id: "1247550020"
      route_id: "32"
    }
    stop_time_update {
      departure {
        time: 1455118786
      }
      stop_id: "1756"
    }
    stop_time_update {
      arrival {
        time: 1455118843
      }
      stop_id: "1757"
    }
```

...we can infer that the prediction is for the first stop in the trip.

Similarly, if there is a prediction before `stop_id = 1756` in the feed:

```
trip_update {
    trip {
      trip_id: "1247550020"
      route_id: "32"
    }
    stop_time_update {
      arrival {
        time: 1455118843
      }
      stop_id: "1900"
    }
    stop_time_update {
      arrival {
        time: 1455118786
      }
      stop_id: "1756"
    }
```

...we can infer that the prediction is for the last stop in the trip.

There are two scenarios that we can’t work around, which would still result in erroneous arrival info being shown in OBA if a provider doesn't include `stop_sequence`:
- When there is only a single prediction in the feed for a trip with a loop
- When a loop occurs in the middle of a trip

We're working on implementing the work-around above to handle first/last stop predictions in loop routes.

Hopefully the GTFS-rt proposal will be approved soon, so producers have clear direction that they must include `stop_sequence` if the same stop is visited more than once in a trip.

cc @cagryInside

**Comment by magdalar** [comment]
FWIW, even if the spec does gain clarity, it may not magically fix your data :)

Our own implementation effectively does longest subsequence matching, allowing for pretty much any form of garbage (because we've observed all forms of it).

**Comment by barbeau** [comment]
>FWIW, even if the spec does gain clarity, it may not magically fix your data :)

Unfortunately true :).

>Our own implementation effectively does longest subsequence matching

@magdalar in loop trips, where the first and last stop are the same, how do you handle a single StopTimeUpdate for this trip, where the `stop_id` is the first/last stop?  Do you just drop it and show schedule data?  Or do you make assumptions based on whether its an arrival/departure?

Our current strategy for OBA is to drop the update.  However, in the feed we're currently working with, the first StopTimeUpdate for the trip is always a departure, and the rest of the trip are arrivals.  So we could make an assumption in this case, but AFAIK there isn't anything is the GTFS-rt spec saying that producers can't provide both an arrival and departure for the first and last stop of the trip (and IIRC Google actually requested that we supply both arrivals and departures for all stops in a previous GTFS-rt feed that we built).  So I don't think this assumption would generalized well.  

Just curious on how Google would handle this case.

**Comment by magdalar** [comment]
@barbeau In a loop trip which provides only a single STU with only a stop_id, it's ambiguous, and we currently don't handle it particularly well, as we don't currently use any time component in the matching (so we'll match it always to the first occurrence in the trip). To fix this, they'd need to provide either a stop_sequence or second STU in order to disambiguate the subsequence, or else we'd probably just recommend they use TripUpdate.delay instead if they're unable.

(We probably could use the same heuristic as we do for TripUpdate.delay on the single-STU case, but it gets edgy, and I don't like sharp edges.)

As for arrival/departure predictions: those recommendations might have been rote, and from awhile ago. These days, I'd probably advise the K.I.S.S. principles, and only one of departure/arrival as makes sense (unless you actually need to demonstrate the trip waiting).
