### ISSUE TITLE
DINO to GTFS converter

### ISSUE THREAD

**Issue by dragoon** [OneBusAway/onebusaway-application-modules#198]
Hello,
on the wiki page it's written that you have importers from DINO data format. Could you please point me where to find them?

**Comment by sheldonabrown** [comment]
Reading
https://github.com/OneBusAway/onebusaway-application-modules/wiki/Real-Time-Data-Configuration-Guide
more carefully, It's not actually OneBusAway that supports DINO, but some
integration work done by bliksemlabs.  The code is here:


https://github.com/bliksemlabs/bliksemintegration/blob/master/importers/dino.py



I found some documentation here:
http://docs.plannerstack.org/en/latest/bliksem/Introduction/

I hope that helps,

Sheldon

**Comment by dragoon** [comment]
Sorry for misunderstanding, I'll try the tool, thank you.

**Comment by aamalik** [comment]
@dragoon did you manage to get it done.

**Comment by dragoon** [comment]
Yes, in the end I've loaded DINO data into postgres, converted it to``bliksemlabs`` postgres format, and then exported GTFS from there.

**Comment by aamalik** [comment]
@dragoon very good to know. I am also using bliksemintegration repository. I have DINO data from VRR. 
I set up the postgres database with postgis and set up the whole schema on my local host as mentioned here: `http://docs.plannerstack.org/en/latest/bliksem/Introduction/`

Now I try to import Dino into postgres using [dino.py](https://github.com/bliksemlabs/bliksemintegration/blob/master/importers/dino.py) 
`python dino.py /Users/khan/dino_vrr_20170307.zip`

but nothing happens. Can you give any tips regarding this please?

**Comment by dragoon** [comment]
@aamalik , this script is not supposed to do anything, it contains just function definitions.
I've wrote a script to import DINO data in my fork: https://github.com/dragoon/bliksemintegration/blob/master/importers/import_dino2posgtres.py

**Comment by aamalik** [comment]
@dragoon can no longer access the link

**Comment by aamalik** [comment]
@dragoon I did the conversion into GTFS for VRR but I dont get any data in transfers.txt and shapes.txt. 
I believe having empty transfers.txt can be very bad since it renders all GTFS data useless. Without having transfers, one cant figure out how stations are connected.
