### ISSUE TITLE
trips-for-route doesn't show all trips

### ISSUE THREAD

**Issue by lubbo** [OneBusAway/onebusaway-application-modules#204]
I'm developing an application that use this feed:
http://transitfeeds.com/p/actv/631/latest
(it will be http://transitfeeds.com/p/actv/631/20170929 after next update)

The trips shown here:
http://transitfeeds.com/p/actv/631/latest/route/98/20171006

are not all retrieved by `trips-for-route`.

It seems that the API return only the trips that starts in the specific time the API was called.
Is it possible?
I've by chance misunderstood `trips-for-route` behaviour?

<BASE_ROUTE>/trips-for-route/ACTV S.p.a_98.json?key=TEST

{
    "code": 200,
    "currentTime": 1507305535612,
    "data": {
        "limitExceeded": false,
        "list": [
            {
                "frequency": null,
                "schedule": null,
                "serviceDate": 1507240800000,
                "situationIds": [],
                "status": null,
                "tripId": "ACTV S.p.a_11106"
            },
            {
                "frequency": null,
                "schedule": null,
                "serviceDate": 1507240800000,
                "situationIds": [],
                "status": null,
                "tripId": "ACTV S.p.a_11023"
            }
        ],
        "outOfRange": false,
        "references": {
            "agencies": [
                {
                    "disclaimer": "",
                    "email": "",
                    "fareUrl": "http://www.veneziaunica.it",
                    "id": "ACTV S.p.a",
                    "lang": "IT",
                    "name": "ACTV S.p.a",
                    "phone": "+390412424",
                    "privateService": false,
                    "timezone": "Europe/Rome",
                    "url": "http://www.actv.it"
                }
            ],
            "routes": [
                {
                    "agencyId": "ACTV S.p.a",
                    "color": "FFFFFF",
                    "description": "",
                    "id": "ACTV S.p.a_98",
                    "longName": "P.le Roma (Hotel S. Chiar - Casino' di Venezia",
                    "shortName": "BLU",
                    "textColor": "000000",
                    "type": 4,
                    "url": ""
                },
                {
                    "agencyId": "ACTV S.p.a",
                    "color": "FFFFFF",
                    "description": "",
                    "id": "ACTV S.p.a_99",
                    "longName": "Casino' di Venezia - P.le Roma (Hotel S. Chiar",
                    "shortName": "BLU",
                    "textColor": "000000",
                    "type": 4,
                    "url": ""
                }
            ],
            "situations": [],
            "stops": [],
            "trips": [
                {
                    "blockId": "ACTV S.p.a_160112",
                    "directionId": "0",
                    "id": "ACTV S.p.a_11106",
                    "routeId": "ACTV S.p.a_98",
                    "routeShortName": "",
                    "serviceId": "ACTV S.p.a_793006_000",
                    "shapeId": "ACTV S.p.a_98_shp",
                    "timeZone": "",
                    "tripHeadsign": "Casino' di Venezia",
                    "tripShortName": ""
                },
                {
                    "blockId": "ACTV S.p.a_160111",
                    "directionId": "1",
                    "id": "ACTV S.p.a_11023",
                    "routeId": "ACTV S.p.a_99",
                    "routeShortName": "",
                    "serviceId": "ACTV S.p.a_793006_000",
                    "shapeId": "ACTV S.p.a_99_shp",
                    "timeZone": "",
                    "tripHeadsign": "P.le Roma (Hotel S. Chiar",
                    "tripShortName": ""
                }
            ]
        }
    },
    "text": "OK",
    "version": 2
}

**Comment by barbeau** [comment]
@lubbo I believe this is intended behavior for the `trips-for-route` API.

From http://developer.onebusaway.org/modules/onebusaway-application-modules/current/api/where/methods/trips-for-route.html, for parameters:

>time - by default, the method returns the status of the system right now. However, the system can also be queried at a specific time. This can be useful for testing. See timestamps for details on the format of the time parameter.

...and the response:

>The response is a list of <tripDetails/> element that captures extended details about each active trip. The set of active trips includes any trip that serves that specified route that is currently active.

I'm going to close as working-as-intended, but let me know if you still think this is working incorrectly.
