### ISSUE TITLE
services/webapp 500 (Internal Server Error)

### ISSUE THREAD

**Issue by WEMAPP** [OneBusAway/onebusaway-application-modules#213]
Excuse me but I can not understand what an error it may be.
If I try to publish a webapp if the webapp I call onebusaway-webapp in the map you can see the stops, if you change the name in onebusaway-webapp-transitagency I get the following error:

1A32A2A40648B988B58733184087ADE9.cache.html:2495 POST http://myurl/services/webapp 404 (Not Found)

Thanks

**Comment by barbeau** [comment]
@WEMAPP Sorry you're having problems!  We use the Github issue tracker for bug tracking, so I'm going to close out this issue.  Please post your questions to https://groups.google.com/forum/#!forum/onebusaway-developers, and please be sure to include the exact steps you've taken to get the OBA server up and running, and what OBA server version and Java version you're using.  If we determine it's a bug with OBA we'll open a new issue here.
