### ISSUE TITLE
Remove references to accounts and login from website

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-application-modules#221]
A user was confused by the references on the puget sound instance of the OBA server to user accounts (see http://pugetsound.onebusaway.org/user/index.action). I don't believe the features described on this page exist—at least not in a functional way:

> Why get a registered account? You can:
> 
> Manage your stop bookmarks on the web and then access them on your phone
> Save and access your preferences across multiple computers
> More features to come

and so this verbiage should be stripped from the site.

**Comment by thewellington** [comment]
Or more better; just make the feature available so that every time I get a new phone I don't have to set up my bookmarks all over again

**Comment by barbeau** [comment]
This feature exists, but it's specific to the OBA website (desktop and mobile versions):
http://pugetsound.onebusaway.org/login.action

I agree that this should be clarified (i.e., it doesn't currently apply to the native apps).  Better yet, if someone would fund adding sync across devices and website as @thewellington mentions, that would be ideal.

**Comment by aaronbrethorst** [comment]
mooted by new UI
