### ISSUE TITLE
Feature Request: Better UI/UX

### ISSUE THREAD

**Issue by iamclaytonray** [OneBusAway/onebusaway-application-modules#222]
Would you allow a PR for a better design system? Currently, the UI is all over the place and it makes it very hard for users (like me) to actually use the website. Fortunately, I'm also a dev + designer so I can do the UI. Thanks!

**Comment by barbeau** [comment]
@iamclaytonray Thanks for reaching out! Are you talking about this website? http://tampa.onebusaway.org/

General high-level design suggestions are welcome - I think we'd want some feedback from others working on the site to make sure your suggestions are in-line with what's planned/expected from agencies before you sink work into development.

cc @sheldonabrown

**Comment by barbeau** [comment]
@iamclaytonray Also, note that this is a white-labeled UI used in other regions such as NYC MTA (https://bustime.mta.info/) and WMATA in DC (https://buseta.wmata.com/):
https://github.com/OneBusAway/onebusaway-application-modules/wiki/Enterprise-Webapp-Configuration

**Comment by iamclaytonray** [comment]
Yes, sorry. Forgot to include which specific website. While I'd love to do a complete redesign, if I could spend a little time working on the sidebar (the list of routes), that would be great. As a user, I find it annoying trying to click my specific stop because content is constantly being pushed from the `transform`s. Maybe adding a little more space between each list item and doing a transition of 200ms - 300ms would greatly improve UX.

**Comment by sheldonabrown** [comment]
As Sean said, we are happy to look at design improvements and even PRs, but I have to admit I still don't understand the specific complaint here?

Are we talking the mobile UI (not the native apps) when viewed with limited screen support?

We added a user-requested refresh to that page -- is that causing you to lose your stop?  Some screenshots would help a lot here I suspect.
