### ISSUE TITLE
Removing an agency in transformer, does not remove fares with derived routes.

### ISSUE THREAD

**Issue by skinkie** [OneBusAway/onebusaway-application-modules#231]
I think the issue is clear. I am trying to remove an agency.

```json
{"op":"remove","match":{"file":"agency.txt","agency_id":"63"}}
```

The result is a GTFS container with the agency removed. But it seems that the fare_rules.txt file is not being processed for the routes the agency might have defined but that have been removed with the above operation.

**Comment by barbeau** [comment]
@skinkie I'm moving this issue to the GitHub repo with the tools at https://github.com/OneBusAway/onebusaway-gtfs-modules/issues/130.
