### ISSUE TITLE
How does one obtain an API Key?

### ISSUE THREAD

**Issue by GrantBirki** [OneBusAway/onebusaway-application-modules#236]
I am currently testing out the public api (http://api.pugetsound.onebusaway.org/api/where/arrivals-and-departures-for-stop/1_75403.xml?key=TEST) and using the TEST Api key. How can I go about obtaining my own key?

**Comment by sheldonabrown** [comment]
Sorry, it looks like that information was moved off of the soundtransit website.  I'll follow up and see if it can be added back.

In the meantime, send an email to OBA_API_KEY@soundtransit.org with
1) your Name
2) Any company you are associated with
3) Purpose of usage
4) A statement agreeing to the terms of usage at:
https://www.soundtransit.org/help-contacts/business-information/open-transit-data-otd/transit-data-terms-use

**Comment by GrantBirki** [comment]
Wanted to follow up. I emailed OBA_API_KEY@soundtransit.org and received an API key for my personal project right away. Thanks!
