### ISSUE TITLE
webapp doesn't show stops on Safari browser

### ISSUE THREAD

**Issue by alanborning** [OneBusAway/onebusaway-application-modules#239]
If you zoom in on the webapp using Chrome or Firefox, the display will show bus stops, even if a route or stop isn't selected.  On Safari the stops don't show unless you select a route or stop.

**Comment by sheldonabrown** [comment]
Resolved with recent update.

**Comment by barbeau** [comment]
@sheldonabrown On Chrome (at least) for Tampa bus stops also appear to be missing

**Comment by sheldonabrown** [comment]
Yes -- sorry, I should have been more explicit.  The code has been fixed, I need to schedule a deployment to resolve it in production.
