### ISSUE TITLE
Quickstart/documentation for V2?

### ISSUE THREAD

**Issue by dudebrains01** [OneBusAway/onebusaway-application-modules#243]
Hey folks!
I was wondering if there was a quickstart edition of OneBusAway Version 2.
I did see a branch called "onebusaway-quickstart", however, there is no documentation or readme with instructions on how to use it.

Could somebody please help me?

Thank you,
Brody Flannigan

**Comment by barbeau** [comment]
@dudebrains01 Good question! See here:
https://github.com/OneBusAway/onebusaway-application-modules/wiki/OneBusAway-Quickstart-Guide

In short - to my knowledge there isn't a working Quickstart for v2 yet, but there is a Docker image (still under development) that you can try.

I'll close this out for cleanup, but feel free to comment more.

**Comment by barbeau** [comment]
Acutally, here's the issue for QuickStart in v2, so let's continue the discussion there:
https://github.com/OneBusAway/onebusaway-application-modules/issues/220
