### ISSUE TITLE
Suggestion - Online bundle building service

### ISSUE THREAD

**Issue by brodyFlannigan** [OneBusAway/onebusaway-application-modules#246]
Hey folks,
With my difficulties involving bundle building (see #244) having not come to an end, I was thinking it could be interesting to have an online service to build bundles (e.g. I upload my GTFS file and enter my GTFS-RT URLs, hit "go" and boom, I have a bundle - possibly in a .zip file)
This way, less experienced users (like me!) could just bypass errors and run the already-compiled bundle via the quickstart interface.
GTFS-to-HTML recently launched a similar service and it is absolutely wonderful. You can see it [here](https://gtfstohtml.com/)

**Comment by metodi-milchev** [comment]
Absolutely agree with this suggestion! Will be very useful.

**Comment by aaronbrethorst** [comment]
I think this issue has been partially addressed by the improvements to the [OBA Docker image](https://github.com/onebusaway/onebusaway-docker) and is also rendered moot by the soft deprecation of Quickstart
