### ISSUE TITLE
Change sign mode "NOW" text in onebusaway-combined-webapp-1.1.19-full

### ISSUE THREAD

**Issue by dudebrains01** [OneBusAway/onebusaway-application-modules#254]
The title pretty much says it all.

I am seeking a way to change the "NOW" text in sign mode to display "0" instead. I have looked in a lot of places but can't seem to find it.

I'm running onebusaway-combined-webapp-1.1.19-full in tomcat9.

Thanks ahead of time.

**Comment by barbeau** [comment]
IIRC in all the v1 releases the web UI is written in Google Web Toolkit (GWT), which is a bit of a pain to work with. To be honest I don't know if the toolchain still works, as it fell out of favor in web development a while back.

More on GWT and the web UI is here:
https://github.com/OneBusAway/onebusaway-application-modules/wiki/Webapp-Configuration-Guide

So you'd need to hunt down where this is stored in the Java, which would then get compiled down to Javascript using GWT.

oba-app-modules v2 uses a normal Javascript web UI.

**Comment by dudebrains01** [comment]
Thanks!

I will look into that.

**Comment by dudebrains01** [comment]
Found it!
It was under WEB-INF.Classes.org.onebusaway.webapp.actions.bundles
The file is ArrivalAndDepartureMessages.properties

Closing this issue!
