### ISSUE TITLE
Upgrade to GMaps v3 - V2 API dies May 20 2013

### ISSUE THREAD

**Issue by nalbion** [OneBusAway/onebusaway-application-modules#26]
https://developers.google.com/maps/documentation/javascript/v2/basics
"Note: The Google Maps JavaScript API Version 2 has been officially deprecated as of May 19, 2010. The V2 API will continue to work until May 19, 2013. We encourage you to migrate your code to version 3 of the Maps JavaScript API."

http://code.google.com/p/gwt-google-maps-v3/
"This project will soon be merged into gwt-google-apis and hence is depricated"

http://code.google.com/p/gwt-google-apis/wiki/MapsFAQ#How_can_I_use_GWT_with_Maps_API_3.0?
"As of the gwt-maps-1.1 release, the current bindings are only compatible with the Maps v2 APIs. You can use JSNI methods to interface with the Maps v3 API"

**Comment by aaronbrethorst** [comment]
I assume this must have long since been resolved with the ACTA web app UI
