### ISSUE TITLE
Stop markers are not visible at the maximum zoom level

### ISSUE THREAD

**Issue by nalbion** [OneBusAway/onebusaway-application-modules#27]
`org.onebusaway.webapp.gwt.where_library.view.stops.onSuccess()` calls

```
addOverlayAtZoom(largerMarker, 17, 20);
```

...assuming that the maximum zoom level supported by Google Maps is 20.

According to [this post](https://groups.google.com/forum/?fromgroups=#!topic/google-maps-api/LTmGBAumPLk) some locations (such as Australia) support zoom level 22.

`.getMaxZoomAtLatLng()` does not seem to be supported in GWT, so just hard-code the upper limit as 22:

```
addOverlayAtZoom(largerMarker, 17, 22);
```

**Comment by aaronbrethorst** [comment]
GWT UI has been dead for many years.
