### ISSUE TITLE
Confusion about Wiki Home page

### ISSUE THREAD

**Issue by dancesWithCycles** [OneBusAway/onebusaway-application-modules#317]
Hi folks,
Thank you so much for providing this repo.

I am far away from being a GitHub expert. For instance, I am wondering why I do not find the Wiki [Home](https://github.com/OneBusAway/onebusaway-application-modules/wiki) page as part of the source files. That Wiki Home page is the origin of my confusion. It is listing the following dependencies.

```
    mvn 3.5.4
    java 1.11.x
    mysql 5.8
```
To the best of my memory and [this](https://en.wikipedia.org/wiki/MySQL) page, there is no ```mysql 5.8``` version. Do you mean version ```8``` by any chance?

Now it is probably obvious that I am also not a mysql expert.

If the home page has a typo and you point me onto the sources I might support the respective update.

Cheers!

**Comment by sheldonabrown** [comment]
Thanks for catching that, it should be mysql 5.7.  Corrected the wiki page.
