### ISSUE TITLE
Sign mode v2 vs v1

### ISSUE THREAD

**Issue by wkulesza** [OneBusAway/onebusaway-application-modules#333]
Hi,
v2 seems not to have the features of v1, including: route=X_Y, minutesBefore=N and minutesAfter=N.
Is there a way to enable them ?

**Comment by sheldonabrown** [comment]
Sign mode v2 was a re-write, it wasn't meant to be feature compatible.
With that said, if you have the v1 sign deployed it should be hard to bring it back, we did that for the legacy iphone mobile view.
