### ISSUE TITLE
Method: arrivals-and-departures-for-location - HTTP Status 404 – Not Found

### ISSUE THREAD

**Issue by sandorbogyo** [OneBusAway/onebusaway-application-modules#336]
Hello,

As I was reading the documentation of the RESTful API, I noticed that the arrivals-and-departures-for-location method does not work. 

Has it been deleted on purpose or am I making a mistake?

http://api.pugetsound.onebusaway.org/api/where/arrivals-and-departures-for-location.xml?key=TEST&lat=47.653&lon=-122.307&latSpan=0.008&lonSpan=0.008

http://developer.onebusaway.org/modules/onebusaway-application-modules/current/api/where/methods/arrivals-and-departures-for-location.html

Regards,

**Comment by aaronbrethorst** [comment]
The URL you provide seems to work fine for me, as long you enter a key that won't be rate-limited.
