### ISSUE TITLE
stops-for-route docs for stopGroup missing <id>

### ISSUE THREAD

**Issue by dxrdxr** [OneBusAway/onebusaway-application-modules#42]
The docs for stops-for-route contains the <stopGroup> element but does not document nor show the <id> element which is returned in the sample query.

**Comment by lorainekv** [comment]
I think this can be closed - a commit from a PR merged in 5/2016 addresses this documentation issue.

https://github.com/OneBusAway/onebusaway-application-modules/pull/169/commits/f601cdc81906ac400e955d5a705ec6db17c0ad3c

**Comment by barbeau** [comment]
Thanks @lorainekv !
