### ISSUE TITLE
maxCount does not limit agencies-with-coverage

### ISSUE THREAD

**Issue by dxrdxr** [OneBusAway/onebusaway-application-modules#45]
Agencies-with-coverage returns a <list> element which by definitiion allows a caller to limit the number of entries returned using the maxCount parameter.

Setting the maxCount=1 will still return 9 elements.

http://api.onebusaway.org/api/where/agencies-with-coverage.xml?key=TEST&version=2&includeReferences=true&maxCount=1

**Comment by aaronbrethorst** [comment]
current API documentation hedges on the language ("many"). I think it's good enough.
