### ISSUE TITLE
Implement REST API to retrieve OBA build version info

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-application-modules#47]
As discussed in the multi-region proposal (https://docs.google.com/document/d/1hYvqUWRAYk5WLM00ZquC7hKbffvrDSOJ8LpHtz5i9Xk/edit?usp=sharing), it would be helpful to be able to  retrieve the build version of an OBA server.

Build info is useful when trying to debug varying behavior in different OBA server instances, to determine the last commit in the current build as well as the major/minor/incremental version.  For example, this allows us to determine if a particular patch has been applied to the server that is supposed to have fixed an issue that is still occurring.

OpenTripPlanner exposes a similar REST API:

https://github.com/openplans/OpenTripPlanner/blob/master/otp-rest-api/src/main/java/org/opentripplanner/api/ws/ServerInfo.java

Example REST API endpoint in a working OTP server:

http://rtp.trimet.org/opentripplanner-api-webapp/ws/serverinfo

API response should include at least the following fields in both JSON and XML formats:

```
<obaVersionInfo>
    <version>0.9.1-SNAPSHOT</version>
    <major>0</major>
    <minor>9</minor>
    <incremental>1</incremental>
    <qualifier>SNAPSHOT</qualifier>
    <commit>de91d05ef4bff7d22ef0b3bec8991625b3b2c797</commit>
</obaVersionInfo>
```

**Comment by aaronbrethorst** [comment]
the config.json endpoint provides almost everything asked for here. I've opened a task to document it here: https://github.com/OneBusAway/onebusaway-docs/issues/26
