### ISSUE TITLE
Implement OneBusAway Glassware for Google Glass

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-application-modules#60]
Having real-time transit information available for favorite/bookmarked stops from OneBusAway via Google Glass seems pretty compelling.  Viewing estimated arrival transit info seems to fit the Glass model of quickly checking information well, with typical interactions that last a very short amount of time (e.g., 15 seconds).  This ticket is intended to capture what we know about OBA and Glass, and track any progress towards implementation.

It seems that OBA Glassware could be implemented fairly easily using the [Google Mirror API](https://developers.google.com/glass/about).  In this model, the OBA Glassware is actually a web application that pushes information to Glass devices, and receives callbacks from user actions, via Google's Mirror API services.  The Mirror API then takes care of syncing information with the user's Glass, and pushing callbacks triggered by user actions to the OBA Glassware service.
#### Installation process for Glassware

Typical "installation" process for Glassware is:
1. User visits website for Glassware via desktop or mobile app browser.
2. User opts-into using the Glassware, including various settings for how frequently information is updated and the number of notification, which results in the Glassware being "installed" on the user's Glass.  For OBA, in the first iteration I imagine that the user would choose which bookmarked stops from their web browser they want to make available in the OBA Glassware (and potentially later, starred stops from mobile apps).
3.  User interacts with cards on Glass to quickly view relevant real-time information.  For OBA, I imagine this would involve seeing a list of favorite stops (including some logic to sort with the closest stop on top), and viewing the real-time arrival info.
#### Implementation

Since Glassware is a webapp, it would be implemented in this Github project, with the UI components in the onebusaway-webapp project, and potentially some of the backend Mirror API operations implemented via the onebusaway-api-webapp.

We should probably wait to implement anything in the official project until #26 (Update to Google Maps API v3, including getting rid of Google Web Toolkit (GWT)) is resolved by Sound Transit, since the method of implementing a new webpage UI to control OBA Glassware settings will be different after GWT is removed.  Also, we really need to get our hands on a real Glass device to test the app (and the actual Mirror API is currently only open to developers with the Google Glass Explorer Edition).  But, we can get started with technical and UI design now.
#### Protocol

Based on my understanding of the [Google Mirror API Usage Stories documentation](https://developers.google.com/glass/stories), here is the proposed usage of the Mirror API to implement OBA Glassware:

![OBA Glassware Protocol](https://docs.google.com/drawings/d/1eCf2DEb4cirm8z8U7ZdTD-OEAm7KDx6T7UthXLkU10c/pub?w=959&h=713)
1.  OBA user visits onebusaway-webapp and subscribes to OBA Glassware by authenticating with OAuth 2.0 (note we're already using OAuth, as evidenced [here](https://github.com/OneBusAway/onebusaway-application-modules/blob/master/onebusaway-webapp/src/main/webapp/WEB-INF/content/login.jspx)).  The user selects which (bookmarked) stops they want available via Glass.  In addition to the usual `glass.timeline` scope, we also request `glass.location` scope access.
2.  After OAuth2.0 completes, OBA Glassware subscribes to updates for the user's location.
3.  OBA Glassware fetches the user's latest location from the location endpoint
4.  OBA Glassware orders the selected user stops by proximity to the user, and creates a `timeline` card that lists the OBA stops and current estimated arrival times.  
5.  To keep this card on the left side of the clock screen, OBA Glassware pins the card.
6.  As the user moves around, their last location is updated
7.  Because OBA Glassware is subscribed to location updates, a notification is to to OBA Glassware by the Mirror API.  This notification links to the `latest` item in the `location` collection.
8.  Based on the notification, OBA Glassware service fetches the user's `latest location` from the `location` collection.  
9.  OBA Glassware re-orders the stops based on user proximity and updates the arrival time information.
10.  OBA Glassware uses the `patch` method to update the body of the timeline item inserted in step 5.
11.  The timeline item also includes a `Refresh` menu item that manually triggers a notification to the OBA Glassware service.  Steps 8, 9, 10 would be performed.

Google Doc Drawing for above protocol image is [here](https://docs.google.com/drawings/d/1eCf2DEb4cirm8z8U7ZdTD-OEAm7KDx6T7UthXLkU10c/edit?usp=sharing).
### Glass UI Design

Since Glass is a completely different user experience than desktop or mobile, the UI design for the OBA cards seen by Glass users should be examined carefully, and tested in real-world situations with actual Glass devices.  The recommended background color is black, since this will be transparent to the user.  And since the background is transparent, high-contrast colors are recommended.  I'm not sure how the default green/red/blue/black colors that we've used for ontime/early/late/no info will come across.

To get us started, here's a possible OBA card mockup for the estimated arrival times card, based on an existing transit example from the Google Mirror API Playground:

![oba_glass_card_mockup](https://f.cloud.github.com/assets/928045/619684/6d0d67d8-ced3-11e2-9716-eaf0c35e4d5f.png)

The "just now" text in the bottom right-hand corner is a default part of the card indicating when it was updated.  

You can paste the below HTML into the [Mirror API Playground page](https://developers.google.com/glass/playground) (just click on the second card template at the bottom that uses HTML, and then the "HTML" button before pasting into textbox), and it will render the above image that you can then edit and play with:

```
<article>
  <section>
    <table class="text-small">
      <tbody>
        <tr>
          <td>
<b>5</b> - N. to University Area TC</td>
          <td>
            <div class="text align-right" style="color : green;">in <b>5</b> min</div>
        </td>
        </tr>
        <tr>
          <td>
            <b>15</b> - S. to Westshore TC</td>
          <td>
            <div class="text align-right muted" style="color : green;">in <b>7</b> min</div>
          </td>
        </tr>
        <tr>
          <td>
            <b>400</b> - S. to Downtown
          </td>
          <td>
            <div class="align-right muted " style="color : red;">in <b>16</b> min</div>
          </td>
        </tr>
        <tr>
          <td>
            <b>24</b> - E. to Netpark TC
          </td>
          <td>
            <div class="align-right muted">in <b>21</b> min</div>
          </td>
        </tr>
      </tbody>
    </table>
  </section>
  <footer>
    <img src="https://mirror-api-playground.appspot.com/links/icons_30_0025_geo_transit.png" class="left">
    <p>Alumni Dr. @ Laurel Dr</p>
  </footer>
</article>

```

I welcome any comments, suggestions, feedback on the above!  Also, if you're a good designer, please improve the above UI design! :)

**Comment by aaronbrethorst** [comment]
mooted.
