### ISSUE TITLE
Port onebusaway-phone to use Twilio instead of Asterisk

### ISSUE THREAD

**Issue by sheldonabrown** [OneBusAway/onebusaway-application-modules#97]

**Comment by mikek163** [comment]
Hi Sheldon, I have SMS & Mobile working off of OBA for company LogicTree LLC. I am starting to integrate IVR and wanted to ask where you stand with the switch to Twillio. Also, does it mean Asterisk will not work with OBA-phone? I would appreciate if you could share the road-map so I can align ours with it.

**Comment by sheldonabrown** [comment]
Hi Mike,

The implementaton of Twilio is wrapping up development.  I hope to have it released soon, based on some code reviews and code cleanup/configuration taking place internally.

It is open source and available, but its currently on a fork/branch until its ready for public usage. 

The twilio implementation is in a new module so as to no disturb the existing onebusaway-phone webapp.

**Comment by landonreed** [comment]
@sheldonabrown has your team produced any documentation for the `onebusaway-twilio-webapp` (just curious even though it's still in dev)?  I'm basically just wondering if the webapp takes a `data-sources.xml` file similar to the one in the `default-resources` directory under `onebusaway-phone-webapp`.

**Comment by sheldonabrown** [comment]
Sorry, no documentation yet.  There is still some cleanup left I hope to
get to shortly.

But yes, same pattern as onebusaway-phone-webapp (its essentially a direct
port).  Contact me directly if you are trying to set this up and I can help
you with the data-sources.xml.
